Eskaney/Areas/Apartments/Controllers/ApartmentsController.cs
using Eskaney.Models;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;

namespace Eskaney.Areas.Apartments.Controllers
{
    public class ApartmentsController : Controller
    {
        private Eskaney_Context db = new Eskaney_Context();

        // GET: Apartments/Apartments
        public ActionResult Home()
        {
            ViewModel VM = new ViewModel();
            VM.List_Of_Apartments = db.Apartments.ToList();

            VM.List_Of_Housings = db.Housings.ToList();

            List<Company> companies = db.Companies.ToList();

            List<Apartment> apartments = db.Apartments.ToList();

            List<Housing> housings = db.Housings.ToList();

            List<City> cityName = db.Cities.ToList();

            List<Picture> pictures = db.Pictures.ToList();


            var MM = from A in apartments
                     join h in housings on A.Housing_ID equals h.ID into table1
                     from h in table1.DefaultIfEmpty()
                     join c in cityName on h.City_ID equals c.ID into table2
                     from c in table2.DefaultIfEmpty()


                     select new ViewModel { City = c, Apartment = A, Housing = h };
            
            return View(MM);
            //return View(VM);
        }

        [HttpGet]
        public ActionResult FillApartments()
        {
            List<Apartment> apartments = db.Apartments.ToList();
            return Json(apartments, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public /*string*/ActionResult GetCity(int id)
        {

            var city = (from a in db.Housings
                            //join b in db.Cities on a.City_ID equals b.ID
                        where a.ID == id
                        select new
                        {
                            ID = a.City_ID,
                            Name = a.city.Name,
                            Location = a.Location
                        }).FirstOrDefault();

            return Json(city, JsonRequestBehavior.AllowGet);
            //return city.ToString();

        }



        public ActionResult Add_Apart(int id)
        {
            if (Session["Company"] != null)
            {
                var Ap = db.Apartments.Where(a => a.Housing_ID == id).ToList().FirstOrDefault();
                Ap.Housing_ID = id;
                TempData["HousingID"] = id;
                ViewBag.ID = id;
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Home", new { area = "Home" });
            }
        }

        [HttpPost]
        public ActionResult Add_Apart(int id, Apartment apartment)
        {
            if (Session["Company"] != null)
            {
                if (ModelState.IsValid)
                {
                    apartment.Housing_ID = id;
                    db.Apartments.Add(apartment);
                    db.SaveChanges();
                    return RedirectToAction("My_Ads", new { @id = apartment.Housing_ID });
                }

                apartment.Housing_ID = id;
                TempData["HousingID"] = id;
                ViewBag.ID = id;
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Home", new { area = "Home" });
            }
        }

        public ActionResult My_Ads(int? id)
        {
            List<Apartment> apartments = db.Apartments.Where(a => a.Housing_ID == id).ToList();
            var aa = db.Pictures.Where(a => a.Apartment_ID == id).FirstOrDefault();
            //ViewBag.Logo = aa.Url;
            //TempData["Pic"] = aa.Url;
            TempData["HousingID"] = id;
            ViewBag.ID = id;
            return View(apartments);
        }

    }
}

Eskaney/Areas/Home/Controllers/HomeController.cs
using Eskaney.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Twilio;
using Twilio.Rest.Api.V2010.Account;
using Twilio.Types;

namespace Eskaney.Areas.Home.Controllers
{
    public class HomeController : Controller
    {
        private readonly Eskaney_Context _Context;

        public HomeController()
        {
            _Context = new Eskaney_Context();
        }

        private Eskaney_Context db = new Eskaney_Context();


        // GET: Home/Home
        [HttpGet]
        public ActionResult Home()
        {

            Session["Admin"] = null;
            Session["Company"] = null;

            return View();
        }


        public ActionResult Test()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Login()
        {
            Session["Admin"] = null;
            Session["Company"] = null;
            return View();
        }

        public ActionResult Logout()
        {
            Session["Admin"] = null;
            Session["Company"] = null;
            return RedirectToAction("Home", "Home", new { area = "Home"});
        }

        [HttpPost]
        public ActionResult Login([Bind(Include = "Email,Password")]Company company)
        {
            var rec = db.Companies.Where(a => a.Email == company.Email && a.Password == company.Password).ToList().FirstOrDefault();

            if (rec != null)
            {
                if (rec.Name == "Basil")
                {
                    Session["Admin"] = rec.Name;
                    Session["AdminLogo"] = rec.Logo;
                    return RedirectToAction("AdminHome", "Companies", new { area = "Admin_Page" });
                }
                else
                {
                    Session["Company"] = rec.Name;
                    TempData["Logo"] = rec.Logo;
                    return RedirectToAction("Chose_Project", "Housings", new { area = "Housing_Projects", id = rec.ID });
                }
            }
            else
            {
                ViewBag.Error = "Invalid User";
                return View(company);
            }
        }






        public ActionResult Test2()
        {
            TempData["ID"] = 1;
            return View();
        }

        public List<Housing> FillHousings(int id)
        {
            List<Housing> housings = db.Housings.Where(a => a.Company_ID == id).Include(h => h.city).Include(h => h.company).Include(h => h.country).ToList();
            return housings;
        }

        public ActionResult Meterial_Details(int id)
        {
            var rec = db.Housings.Where(a => a.ID == id).ToList().FirstOrDefault();

            TempData["ID"] = rec.ID;
            TempData["ProjectName"] = rec.Project_Name;
            TempData["Logo"] = rec.Logo;

            ViewBag.Logo = rec.Logo;
            ViewBag.ID = rec.ID;
            return View();
        }

        public JsonResult getMaterials(int id)
        {
            ViewData["ID"] = id;
            var Material = db.Material_Expenses.Where(a => a.Housing_ID == id).ToList();
            return Json(Material, JsonRequestBehavior.AllowGet);
        }


        public ActionResult Test3()
        {
            List<Housing> housings = _Context.Housings.ToList();
            return View(housings);
        }

        public ActionResult Test4()
        {
            Session["Test"] = "Test";
            return View();
        }

    }
}

Eskaney/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Eskaney.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Home()
        {
            return RedirectToAction("Home", "Home", new { area = "Home" });
            //return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Eskaney/Areas/Home/Views/Home/Home.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Areas/Home/Views/Shared/_Home.cshtml";
}

@section Head{
    <script>
        $(document).ready(function () {

            $("#Home").addClass("active");

            $("#myForm").addClass("none");


            $("#animate").animate({
                top: '50%',
                left: '600px',
                borderRadius: '15px'
            },2000);
        });


        function myFunction() {
            var x = document.getElementById("myDIV");
            var y = document.getElementById("HomeImage")
            if (x.style.display === "none") {
                y.style.display = "none";
                x.style.display = "block";
            } else {
                y.style.display = "block";
                x.style.display = "none";
            }
        }


    </script>

    <style>

        @@media (min-width: 768px) {
            .col-md-4 {
                -ms-flex: 0 0 33.333333%;
                flex: 0 0 33.333333%;
                max-width: 33.333333%;
                margin-top: 160px;
            }
        }

        @@media (min-width: 1200px) {
            .mt-xl-5, .my-xl-5 {
                margin-top: 13% !important;
            }
        }

        @@media (min-width: 1200px) {
            .mt-xl-8 {
                margin-top: 15rem !important;
            }
        }

        @@media (min-width: 425px) and (max-width: 576px) {
            .mask {
                height: 684px;
            }

            .text {
                margin-top: 100px;
            }
        }

        @@media (max-width: 1440px) and (min-width: 1025px) {
            .mask {
                height: 557px;
            }
        }

        @@media (max-width: 424px) and (min-width: 376px) {
            .mask {
                height: 470px;
            }
        }

        @@media (max-width: 1024px) and (min-width: 767px) {
            .mask {
                height: 470px;
            }

            .text {
                margin-top: 70px;
            }
        }

        @@media (max-width: 767px) {
            .text {
                margin-top: 100px;
            }
        }

        @@media(max-width: 740px) {
            html, body, header, .view {
                height: 790px;
            }
        }
    </style>


}

@section Body{



    <!-- Full Page Intro -->

    <div class="" style="background-image: url('../../../../Image/architecture.jpg');
        background-repeat: no-repeat;
        background-size: cover;
        background-position: center center;
        ">
        <!-- Mask & flexbox options-->
        <div class="mask rgba-gradient align-items-center" style="">

            <div class="container">
                <!--Grid row-->
                <div class="row">
                    <!--Grid column-->
                    <div class="text col-md-6 white-text text-center text-md-left mt-xl-5 mb-5 wow fadeInLeft" data-wow-delay="0.3s">
                        <h1 class="h1-responsive font-weight-bold mt-sm-5">Eskaney </h1>
                        <hr class="hr-light">
                        <h4 class="mb-4">
                            Help you to create your real estate more regularly
                            and manage your project expenses easily
                            and more accurately and keep your information when you need it..
                            </h4>
                            <a class="btn btn-white" id="Login" href="@Url.Action("Login" , "Home" , new { area="Home" })" style="border-radius: 15px 0px;">Login</a>
                            <a class="btn btn-outline-white" style="border-radius: 0px 15px;">Take a tour</a>
                            <a class="btn btn-blue" href="@Url.Action("Home" , "Apartments" , new { area="Apartments" })" style="border-radius: 15px 0px;">For Sale</a>

                            <a class="btn btn-blue" onclick="myFunction()" style="border-radius: 15px 15px;margin-left: 1115px;margin-top: 35px;padding:0px;"><img src="~/Image/iconfinder_messages_16_171351.png" style="width: 45px;" /></a>
                    </div>
                    <!--Grid column-->
                    <!--Grid column-->
                    <div id="animate" class="col-lg-5 col-md-4 col-xl-5 mt-xl-6 mt-md-6 col-sm-9 offset-md-1 offset-sm-1 col-10 offset-1 mt-xl-8 wow fadeInRight d-none d-lg-block d-xl-block" data-wow-delay="0.3s" style="padding: 0;margin-top: -50%;margin-left:-400px;">
                        @*<img src="https://mdbootstrap.com/img/Mockups/Transparent/Small/admin-new.png" alt="" class="img-fluid">*@

                        <img id="HomeImage" src="~/Image/HomePage.png" alt="" class="img-fluid" style="height: 230px;width: 100%;" />


                        <iframe id="myDIV" src="https://powerva.microsoft.com/webchat/bots/0677717b-cfd0-4347-91ed-0e59acf3b36d" frameborder="0" style="width: 100%; height: 415px; display: none; margin-top: -155px;"></iframe>
                        
                    </div>



                    <!--Grid column-->
                    <div class="col-lg-5 col-md-4 col-xl-5 mt-xl-6 mt-md-6 col-sm-9 offset-md-1 offset-sm-1 col-10 offset-1 mt-xl-8 wow fadeInRight d-block d-sm-block d-md-block d-lg-block d-xl-none" data-wow-delay="0.3s" style="padding: 0;">
                        @*<img src="https://mdbootstrap.com/img/Mockups/Transparent/Small/admin-new.png" alt="" class="img-fluid">*@

                        <img src="~/Image/HomePage.png" alt="" class="img-fluid" style="height: 230px;width: 100%;" />
                    </div>
                    <!--Grid column-->
                </div>
                <!--Grid row-->
            </div>
            <!-- Content -->
        </div>


    </div>




}

Eskaney/Areas/Home/Views/Home/Login.cshtml
@model Eskaney.Models.Company

@{
    ViewBag.Title = "Login";
    Layout = "~/Areas/Home/Views/Shared/_Home.cshtml";
}



@section Head{

    <link href="~/Areas/Home/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Areas/Home/fonts/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Areas/Home/fonts/iconic/css/material-design-iconic-font.min.css" rel="stylesheet" />
    <link href="~/Areas/Home/vendor/animate/animate.css" rel="stylesheet" />
    <link href="~/Areas/Home/vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" />
    <link href="~/Areas/Home/vendor/animsition/css/animsition.min.css" rel="stylesheet" />
    <link href="~/Areas/Home/vendor/select2/select2.min.css" rel="stylesheet" />
    <link href="~/Areas/Home/vendor/daterangepicker/daterangepicker.css" rel="stylesheet" />



    <link href="~/Areas/Home/css/util.css" rel="stylesheet" />
    <link href="~/Areas/Home/css/main.css" rel="stylesheet" />
    <!--===============================================================================================-->


    <link href="~/Areas/Home/css/Home_Style.css" rel="stylesheet" />

    <script type="text/javascript">

        $(document).ready(function () {

            $("#animate").animate({
                top: '50%',
                left: '500px',
                borderRadius: '15px'
            }, 2000);

        });
    </script>

    <style>

        @@media (min-width: 768px) {
            .col-md-4 {
                -ms-flex: 0 0 33.333333%;
                flex: 0 0 33.333333%;
                max-width: 33.333333%;
                margin-top: 230px;
            }

            .wrap-input100{
                margin-bottom: 10px;
            }

            .contact100-form-checkbox{
                padding-bottom: 10px;
            }
        }

        @@media (min-width: 1200px) {
            .mt-xl-5, .my-xl-5 {
                margin-top: 13% !important;
            }

            .mt-xl-8 {
                margin-top: 15rem !important;
            }
        }


        @@media (min-width: 1024px) {
            .wrap-login100 {
                padding-bottom: 0px;
                margin-top: 30px;
            }
            .login100-form-title{
                padding: 10px;
            }

            .wrap-input100{
                margin-bottom: 10px;
            }

            .contact100-form-checkbox{
                padding-bottom: 10px;
            }

        }

        @@media (min-width: 1440px) {
            .wrap-login100 {
                margin-top: 60px;
            }
        }

        @@media (min-width: 740px) and (max-width: 1022px) {
            .wrap-login100 {
                padding-bottom: 0px;
                margin-top: 20px;
            }

            .login100-form-title {
                padding: 10px;
            }
        }

        
            .container-login100 {
                margin-top: 30px;
            }
        
    </style>

    <script type="text/javascript">


        function openForm() {
            document.getElementById("myForm").style.display = "block";
        }

        function closeForm() {
            document.getElementById("myForm").style.display = "none";
        }



        // Stop going back after log off
        debugger;
        window.onload = function () { Clear(); }
        function Clear() {
            var Backlen = history.length;
            if (Backlen > 0) history.go(-Backlen);
        }
        /*******************************/





    </script>

    <style>
        @@media (max-width: 750px) {

            #homeImg {
                visibility: hidden;
            }
        }

        @@media (max-width: 750px) {

            .login100-form-title {
                line-height: 0.0;
            }
        }


        @@media (min-width: 320px) and (max-width: 576px) {
            .mask {
                height: 870px;
            }

            .wrap-login100 {
                margin-left: 0;
            }

        }

        @@media (max-width: 1440px) and (min-width: 1025px) {
            .container-login100 {
                 margin-top: 0; 
            }
            .wrap-login100 {
                padding-bottom: 0px;
                margin-top: 65px;
            }
        }

        @@media (max-width: 424px) and (min-width: 376px) {
            .mask {
                height: 470px;
            }
        }

        @@media (max-width: 1024px) and (min-width: 767px) {
            .mask {
                height: 580px;
            }

        }



        @@media(max-width: 740px) {
            html, body, header, .view {
                height: 790px;
            }
        }
    </style>
}



@section Body{

    

    <form action="Login" method="post" class="" style="
        background-image: url('../../../../Image/architecture.jpg');
        background-repeat: no-repeat;
        background-size: cover;
        background-position: center center;">
        <!-- Mask & flexbox options-->
        <div class="mask rgba-gradient align-items-center">
            <div class="container">
                <!--Grid row-->
                <div class="row">
                    <!--Grid column-->
                    <div class="col-md-7 white-text text-center text-md-left mt-xl-4 mt-lg-5 mb-3 mt-sm-5 mt-2 wow fadeInLeft" data-wow-delay="0.3s" style="margin-top: 90px;padding-bottom: 100px">

                        <div class="limiter">
                            <div class="container-login100" style="margin-bottom: -120px;">
                                <div class="wrap-login100" style="padding-bottom: 0px;">
                                    <div class="login100-form validate-form" style="padding: 10px;">
                                        <span class="login100-form-logo">
                                            <img src="~/Image/kisspng-house-home-inspection-real-estate-hughesville-5ce3da57e889d9.7636396815584364399525.png" style="width: 100px;" />
                                        </span>

                                        <span class="login100-form-title p-b-34 p-t-27">
                                            Log in
                                        </span>
                                        <div class="wrap-input100 validate-input" data-validate="Enter Email">
                                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @id = "txtEmail", @class = "input100", type = "text", name = "username", placeholder = "Email" } })
                                            <span class="focus-input100" data-placeholder="&#xf207;"></span>
                                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })

                                        </div>
                                        @*<div class="wrap-input100 validate-input" data-validate="Enter username">
                            <input id="txtName" class="input100" type="text" name="username" placeholder="Username">
                            <span class="focus-input100" data-placeholder="&#xf207;"></span>
                            </div>*@


                                        <div class="wrap-input100 validate-input" data-validate="Enter password" style="margin-top: 25px;">
                                            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @id = "txtPass", @class = "input100", type = "password", name = "pass", placeholder = "Password" } })
                                            <span class="focus-input100" data-placeholder="&#xf191;"></span>
                                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                                        </div>

                                        <div class="contact100-form-checkbox">
                                            <input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
                                            <label class="label-checkbox100" for="ckb1">
                                                Remember me
                                            </label>
                                        </div>


                                        <div class="container-login100-form-btn">
                                            <div>
                                                <input type="submit" value="Login" class="login100-form-btn" />
                                            </div>
                                        </div>

                                        @*<div class="container-login100-form-btn">

                            <input type="submit" value="Login" class="login100-form-btn" />
                            <a id="btnLogin">
                            <span class="login100-form-btn">
                            </a>


                            <button class="login100-form-btn">Login</button>
                            </div>*@

                                        <div class="text-center p-t-90">
                                            <a class="txt1" href="#">
                                                Forgot Password?
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!--Grid column-->
                    <div id="animate" class="col-lg-5 col-md-4 col-xl-5 mt-xl-6 mt-md-6 col-sm-9 offset-md-1 offset-sm-1 col-10 offset-1 mt-xl-8 wow fadeInRight d-none d-lg-block d-xl-block" data-wow-delay="0.3s" style="padding: 0;margin-top: -50%;margin-left:-400px;">
                        @*<img src="https://mdbootstrap.com/img/Mockups/Transparent/Small/admin-new.png" alt="" class="img-fluid">*@

                        <img src="~/Image/HomePage.png" alt="" class="img-fluid" style="height: 230px;width: 100%;" />
                    </div>

                    <!--Grid column-->
                    <div class="col-lg-5 col-md-4 col-xl-5 mt-xl-6 mt-md-6 col-sm-9 offset-md-1 offset-sm-1 col-10 offset-1 mt-xl-8 wow fadeInRight d-block d-sm-block d-md-block d-lg-block d-xl-none" data-wow-delay="0.3s" style="padding: 0;">
                        @*<img src="https://mdbootstrap.com/img/Mockups/Transparent/Small/admin-new.png" alt="" class="img-fluid">*@

                        <img src="~/Image/HomePage.png" alt="" class="img-fluid" style="height: 230px;width: 100%;" />
                    </div>
                    <!--Grid column-->

                    @*<div class="col-lg-5 col-md-4 col-xl-5 col-sm-9 col-10 wow fadeInRight d-none d-sm-block" data-wow-delay="0.3s" style="padding: 0;">
                        <img id="homeImg" src="~/Image/HomePage.png" alt="" class="img-fluid" style="height: 230px;width: 100%;" />
                    </div>*@
                </div>

                <div id="dropDownSelect1"></div>
            </div>
        </div>






        @*<script src="~/Areas/Home/vendor/jquery/jquery-3.2.1.min.js"></script>
            <script src="~/Areas/Home/vendor/animsition/js/animsition.min.js"></script>
            <script src="~/Areas/Home/vendor/bootstrap/js/popper.js"></script>
            <script src="~/Areas/Home/vendor/select2/select2.min.js"></script>


            <script src="~/Areas/Home/vendor/daterangepicker/moment.min.js"></script>
            <script src="~/Areas/Home/vendor/daterangepicker/daterangepicker.js"></script>

            <script src="~/Areas/Home/vendor/countdowntime/countdowntime.js"></script>*@

        <script src="~/Areas/Home/JS/main.js"></script>

    </form>

}

Eskaney/Areas/Home/Views/Home/Test.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewBag.Title</title>

    <link href="~/Scripts/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.4.1.js"></script>

    <link rel="icon" type="image/png" href="~/Areas/Home/images/favicon.ico" />
    <link href="~/Areas/Admin_Page/css/styles.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>

    <!-- for mdb for bootstrab-->
    <link href="~/Content/mdb.min.css" rel="stylesheet" />


    <script src="~/js/jquery-3.3.1.min.js"></script>

    <link href="~/Scripts/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.min.js"></script>

    <script src="~/Scripts/jquery-3.4.1.js">
        
    </script>
    <link href="~/Areas/Home/css/Home_Style.css" rel="stylesheet" />

    <style>
        @@media (min-width: 992px) {
            .navbar-expand-lg .navbar-toggler {
                display: block;
            }
        }
    </style>

</head>
<body class="sb-nav-fixed">

    
    <fieldset>
        <legend>First Name</legend>
        <input type="text" name="name" value="" />
        <button>Ok</button>
    </fieldset>

</body>
</html>

Eskaney/Areas/Home/Views/Home/Test2.cshtml
@*@model Eskaney.Models.ManPowerCoust*@
@model Eskaney.Models.ViewModel
@{
    ViewBag.Title = "Test2";
    Layout = "~/Areas/Home/Views/Shared/_Home.cshtml";
}
@section Head{

    <style>
        /* Extra small devices (portrait phones, less than 576px) */
        @@media (max-width: 575.98px) {
        }

        /* Small devices (landscape phones, 576px and up)*/
        @@media (min-width: 576px) and (max-width: 767.98px) {
        }

        /* Medium devices (tablets, 768px and up)*/
        @@media (min-width: 768px) and (max-width: 991.98px) {
        }

        /* Large devices (desktops, 992px and up)*/
        @@media (min-width: 992px) and (max-width: 1199.98px) {
        }

        /* Extra large devices (large desktops, 1200px and up)*/
        @@media (min-width: 1200px) {
        }


        /*=========================
         Icons
        ================= */

    </style>

    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
}

@section Body{
    <br />
    <br />
    <br />


    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#staticBackdrop">
        Launch static backdrop modal
    </button>

    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    ...
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Understood</button>
                </div>
            </div>
        </div>
    </div>


    <button type="button" class="btn btn-secondary" data-toggle="tooltip" data-placement="left" title="Tooltip on right">
        Tooltip on right
    </button>

}