Eskaney/Models/Material.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Eskaney.Models
{
    public class Material
    {
        public int ID { get; set; }
        public string Material_Name { get; set; }
    }
}

Eskaney/Areas/Housing_Projects/Controllers/MaterialController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Eskaney.Models;

namespace Eskaney.Areas.Housing_Projects.Controllers
{
    public class MaterialController : Controller
    {
        private Eskaney_Context db = new Eskaney_Context();

        // GET: Housing_Projects/Material
        public ActionResult Add_Material(int? id)
        {
            if (Session["Company"] != null)
            {
                var addMat = db.Housings.Where(a => a.ID == id).ToList().FirstOrDefault();
                TempData["HousingID"] = addMat.ID;
                TempData["ProjectName"] = addMat.Project_Name;
                TempData["Logo"] = addMat.Logo;
                var x = addMat.Company_ID;


                var com = db.Companies.Where(a => a.ID == x).FirstOrDefault();
                TempData["CompanyName"] = com.Name;
                ViewBag.Logo = addMat.Logo;
                ViewBag.ID = addMat.ID;

                return View();
            }
            else
            {
                return RedirectToAction("Login", "Home", new { area = "Home" });
            }
        }

        // GET: Housing_Projects/Material/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Material_Expenses material_Expenses = db.Material_Expenses.Find(id);
            if (material_Expenses == null)
            {
                return HttpNotFound();
            }
            return View(material_Expenses);
        }

        // GET: Housing_Projects/Material
        public ActionResult Material_Details(int? id)
        {
            if (Session["Company"] != null)
            {
                var Mat_Det = db.Housings.Where(a => a.ID == id).ToList().FirstOrDefault();
                TempData["HousingID"] = Mat_Det.ID;
                TempData["ProjectName"] = Mat_Det.Project_Name;
                TempData["Logo"] = Mat_Det.Logo;
                var x = Mat_Det.Company_ID;


                var com = db.Companies.Where(a => a.ID == x).FirstOrDefault();
                TempData["CompanyName"] = com.Name;

                ViewBag.Logo = Mat_Det.Logo;
                ViewBag.ID = Mat_Det.ID;

                var Material_Det = db.Material_Expenses.Where(a => a.Housing_ID == id).Include(m => m.housing);

                return View(Material_Det.ToList());
                //ViewBag.Housing_ID = new SelectList(db.Housings, "ID", "Project_Name");
                //return View();
            }
            else
            {
                return RedirectToAction("Login", "Home", new { area = "Home" });
            }
            
        }

        // POST: Housing_Projects/Material/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add_Material(/*[Bind(Include = "ID,Material_Name,Material_Source,Quantity,Date,Coust,EnvoiceNumber,Notes,Housing_ID")] */ int id, Material_Expenses mat_Exp)
        {
            if (Session["Company"] != null)
            {
                if (ModelState.IsValid)
                {
                    mat_Exp.Housing_ID = id;
                    db.Material_Expenses.Add(mat_Exp);
                    db.SaveChanges();
                    return RedirectToAction("Material_Details", new { @id = mat_Exp.Housing_ID });
                }

                mat_Exp.Housing_ID = id;
                TempData["HousingID"] = id;
                ViewBag.ID = id;
                return View(mat_Exp);
            }
            else
            {
                return RedirectToAction("Login", "Home", new { area = "Home" });
            }
        }

        // GET: Housing_Projects/Material/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["Company"] != null)
            {
                var aa = db.Material_Expenses.Where(a => a.ID == id).ToList().FirstOrDefault();
                TempData["HousingID"] = aa.Housing_ID;

                var bb = db.Housings.Where(a => a.ID == aa.Housing_ID).ToList().FirstOrDefault();

                TempData["ProjectName"] = bb.Project_Name;
                TempData["Logo"] = bb.Logo;

                ViewBag.Logo = bb.Logo;
                ViewBag.ID = bb.ID;

                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Material_Expenses material_Expenses = db.Material_Expenses.Find(id);
                if (material_Expenses == null)
                {
                    return HttpNotFound();
                }
                ViewBag.Housing_ID = material_Expenses.Housing_ID;
                //ViewBag.Housing_ID = new SelectList(db.Housings, "ID", "Project_Name", material_Expenses.Housing_ID);
                return View(material_Expenses);
            }
            else
            {
                return RedirectToAction("Login", "Home", new { area = "Home" });
            }
        }

        // POST: Housing_Projects/Material/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(/*[Bind(Include = "ID,Material_Name,Material_Source,Quantity,Date,Coust,EnvoiceNumber,Notes,Housing_ID")]*/ int id, Material_Expenses material_Expenses)
        {
            if (Session["Company"] != null)
            {
                var Mat_Ex = db.Material_Expenses.AsNoTracking().Where(a => a.ID == id).ToList().FirstOrDefault();
                var Housing_ID = Mat_Ex.Housing_ID;
                TempData["HousingID"] = Housing_ID;


                if (ModelState.IsValid)
                {
                    material_Expenses.Housing_ID = Housing_ID;
                    db.Entry(material_Expenses).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Material_Details", new { @id = material_Expenses.Housing_ID });
                }
                ViewBag.Housing_ID = material_Expenses.Housing_ID;
                return View(material_Expenses);
            }
            else
            {
                return RedirectToAction("Login", "Home", new { area = "Home" });
            }
        }

        // GET: Housing_Projects/Material/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["Company"] != null)
            {
                var Mat_Ex = db.Material_Expenses.AsNoTracking().Where(a => a.ID == id).ToList().FirstOrDefault();
                var Housing_ID = Mat_Ex.Housing_ID;
                TempData["HousingID"] = Housing_ID;



                var bb = db.Housings.Where(a => a.ID == Housing_ID).ToList().FirstOrDefault();

                TempData["ProjectName"] = bb.Project_Name;
                TempData["Logo"] = bb.Logo;

                ViewBag.Logo = bb.Logo;
                ViewBag.ID = bb.ID;

                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Material_Expenses material_Expenses = db.Material_Expenses.Find(id);
                if (material_Expenses == null)
                {
                    return HttpNotFound();
                }
                return View(material_Expenses);
            }
            else
            {
                return RedirectToAction("Login", "Home", new { area = "Home" });
            }
        }

        // POST: Housing_Projects/Material/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Session["Company"] != null)
            {
                Material_Expenses material_Expenses = db.Material_Expenses.Find(id);
                db.Material_Expenses.Remove(material_Expenses);
                db.SaveChanges();
                return RedirectToAction("Material_Details", new { @id = material_Expenses.Housing_ID });
            }
            else
            {
                return RedirectToAction("Login", "Home", new { area = "Home" });
            }

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        //public JsonResult getMaterials(int id)
        //{
        //    ViewData["ID"] = id;
        //    var Material = db.Material_Expenses.Where(a => a.Housing_ID == id).ToList();
        //    return Json(Material, JsonRequestBehavior.AllowGet);
        //}
    }
}

Eskaney/Areas/Housing_Projects/Views/Material/Add_Material.cshtml
@model Eskaney.Models.Material_Expenses

@{
    ViewBag.Title = "Add Material";
    Layout = "~/Areas/Housing_Projects/Views/Shared/_Home.cshtml";
}


@section Head{

    <script type="text/javascript">


        $(document).ready(function () {

            $("#Material").addClass("active");
            var test = '@TempData["CompanyName"]'

            debugger
            var Housing_ID = '@TempData["HousingID"]';


            // For Date
            var now = new Date();
            var month = (now.getMonth() + 1);
            var day = now.getDate();
            if (month < 10)
                month = "0" + month;
            if (day < 10)
                day = "0" + day;
            var today = now.getFullYear() + '-' + month + '-' + day;
            $('#txtDate').val(today);
            /********************************/

            $("#txtHousing_ID").val(id);


        });
    </script>

}


@section Body{

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="container">
            <div class="row col-xl-12" style="margin: 0;">
                <img class="offset-xl-5 offset-lg-5 offset-md-5 offset-sm-4 offset-5" src="~/Image/AddMaterial.png" style="width: 80px;margin-top: 40px;" />
            </div>
        </div>

        <div class="card mb-4">
            <div class="card-header"><h4 style="cursor: default;"><i style="margin-right: 20px;" class="fas fa-plus-circle"></i>Add Material Expenses</h4></div>
            <div class="card-body">
                <div class="row" style="margin: 0px 0px;width: 90%;">
                    <div class="md-form form-lg col-lg-3 col-md-4 col-sm-4 col-6 offset-lg-2 offset-sm-2">
                        @Html.TextBoxFor((a => a.Material_Name), htmlAttributes: new { @class = "form-control form-control-lg", @id = "txtMaterialName" })
                        @Html.ValidationMessageFor(a => a.Material_Name, "", new { @class = "text-danger" })
                        @*<input type="text" id="form1" class="form-control form-control-lg">
                            <label for="form1">Material Name</label>*@
                        <label for="txtMaterialName">Material Name</label>
                    </div>
                    <div class="md-form form-lg col-lg-3 col-md-4 col-sm-4 col-6 offset-lg-2 offset-sm-1">
                        @Html.TextBoxFor((a => a.Material_Source), htmlAttributes: new { @class = "form-control form-control-lg", @id = "txtMaterialExpenses" })
                        @Html.ValidationMessageFor(a => a.Material_Source, "", new { @class = "text-danger" })
                        @*<input type="text" id="form1" class="form-control form-control-lg">
                            <label for="form1">Material Exporter</label>*@
                        <label for="txtMaterialExpenses">Material Source</label>
                    </div>
                </div>
                <div class="row" style="margin: 0px 0px;width: 90%;">
                    <div class="md-form form-lg col-lg-3 col-md-4 col-sm-4 col-6 offset-lg-2 offset-sm-2">
                        @Html.TextBoxFor((a => a.Quantity), htmlAttributes: new { @class = "form-control form-control-lg", @id = "txtQuantity" })
                        @Html.ValidationMessageFor(a => a.Quantity, "", new { @class = "text-danger" })
                        @*<input type="text" id="form1" class="form-control form-control-lg">
                            <label for="form1">Quantity</label>*@
                        <label for="txtQuantity">Quantity</label>
                    </div>
                    <div class="md-form form-lg col-lg-3 col-md-4 col-sm-4 col-6 offset-lg-2 offset-sm-1">
                        @Html.TextBoxFor((a => a.Date), htmlAttributes: new { @class = "form-control form-control-lg", @id = "txtDate" })
                        @*<input type="date" id="txtDate" class="form-control form-control-lg">*@
                    </div>
                </div>
                <div class="row" style="margin: 0px 0px;width: 90%;">
                    <div class="md-form form-lg col-lg-3 col-md-4 col-sm-4 col-6 offset-lg-2 offset-sm-2">
                        @Html.TextBoxFor((a => a.Coust), htmlAttributes: new { @class = "form-control form-control-lg", @id = "txtCoust" })
                        @Html.ValidationMessageFor(a => a.Coust, "", new { @class = "text-danger" })
                        @*<input type="text" id="form1" class="form-control form-control-lg">
                            <label for="form1">Coust</label>*@
                        <label for="txtCoust">Coust</label>
                    </div>
                    <div class="md-form form-lg col-lg-3 col-md-4 col-sm-4 col-6 offset-lg-2 offset-sm-1">
                        @Html.TextBoxFor((a => a.EnvoiceNumber), htmlAttributes: new { @class = "form-control form-control-lg", @id = "txtEnvoiceNumber" })
                        @Html.ValidationMessageFor(a => a.EnvoiceNumber, "", new { @class = "text-danger" })
                        @*<input type="text" id="form1" class="form-control form-control-lg">
                            <label for="form1">Notes</label>*@
                        <label for="txtEnvoiceNumber">Envoice Number</label>
                    </div>
                </div>

                <div class="row" style="margin: 0px 0px;width: 90%;">
                    <div class="md-form form-lg col-lg-3 col-md-4 col-sm-4 col-6 offset-lg-2 offset-sm-2">
                        @Html.TextBoxFor((a => a.Notes), htmlAttributes: new { @class = "form-control form-control-lg", @id = "txtNotes" })
                        @Html.ValidationMessageFor(a => a.Notes)
                        @*<input type="text" id="form1" class="form-control form-control-lg">
                            <label for="form1">Notes</label>*@
                        <label for="txtNotes">Notes</label>
                    </div>
                </div>
                <div class="row" style="margin: 0px 0px;width: 90%;">
                    <div class="offset-xl-5 offset-lg-5 offset-md-5 offset-sm-5 offset-4">
                        <input id="btnSave" type="submit" class="btn blue-gradient" name="btnSave" value="Add" style="border-radius: 15px" />
                    </div>
                </div>
            </div>
        </div>
        

    }

}

Eskaney/Areas/Housing_Projects/Views/Material/Delete.cshtml
@model Eskaney.Models.Material_Expenses

@{
    ViewBag.Title = "Delete Material";
    Layout = "~/Areas/Housing_Projects/Views/Shared/_Home.cshtml";
}

@section Head{

    <script type="text/javascript">


        $(document).ready(function () {

            $("#Material").addClass("active");

            var Housing_ID = '@TempData["HousingID"]';
        })

        // Stop going back after log off
        //debugger;
        //if (window.history.forward(1) != null)
        //    window.history.forward(1);
        /*******************************/
    </script>
}


@section Body{

    <div class="container">
        <div class="row col-xl-12" style="margin: 0;">
            <img class="offset-xl-5 offset-lg-5 offset-md-5 offset-sm-4 offset-5" src="~/Image/AddMaterial.png" style="width: 80px;margin-top: 40px;" />
        </div>
    </div>

    <div class="card mb-4">
        <div class="card-header"><h4 style="cursor: default;"><i style="margin-right: 20px;" class="fas fa-trash"></i>Delete Material</h4></div>
        <div class="card-body">
            <h3 style="padding: 10px 80px 40px 80px;">Are you sure you want to delete this?</h3>
            <div class="row" style="margin: 0px 0px;width: 90%;">
                <div class="col-lg-2 offset-lg-2">
                    <label style="font-weight: bolder">@Html.DisplayName("Project Name :")</label>
                </div>
                <div class="col-lg-3">
                    @Html.DisplayFor(model => model.housing.Project_Name, new { htmlAttributes = new { @class = "form-control" } })
                </div>

                <div class="col-lg-2">
                    <label style="font-weight: bolder">@Html.DisplayName("Material Name :")</label>
                </div>
                <div class="col-lg-3">
                    @Html.DisplayFor(model => model.Material_Name, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="row" style="margin: 0px 0px;width: 90%;">
                <div class="col-lg-2 offset-lg-2">
                    <label style="font-weight: bolder">@Html.DisplayName("Material Source :")</label>
                </div>
                <div class="col-lg-3">
                    @Html.DisplayFor(model => model.Material_Source, new { htmlAttributes = new { @class = "form-control" } })
                </div>

                <div class="col-lg-2">
                    <label style="font-weight: bolder">@Html.DisplayName("Quantity :")</label>
                </div>
                <div class="col-lg-3">
                    @Html.DisplayFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="row" style="margin: 0px 0px;width: 90%;">
                <div class="col-lg-2 offset-lg-2">
                    <label style="font-weight: bolder">@Html.DisplayName("Date :")</label>
                </div>
                <div class="col-lg-3">
                    @Html.DisplayFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                </div>

                <div class="col-lg-2">
                    <label style="font-weight: bolder">@Html.DisplayName("Coust :")</label>
                </div>
                <div class="col-lg-3">
                    @Html.DisplayFor(model => model.Coust, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="row" style="margin: 0px 0px;width: 90%;">
                <div class="col-lg-2 offset-lg-2">
                    <label style="font-weight: bolder">@Html.DisplayName("Envoice Number :")</label>
                </div>
                <div class="col-lg-3">
                    @Html.DisplayFor(model => model.EnvoiceNumber, new { htmlAttributes = new { @class = "form-control" } })
                </div>

                <div class="col-lg-2">
                    <label style="font-weight: bolder">@Html.DisplayName("Notes :")</label>
                </div>
                <div class="col-lg-3">
                    @Html.DisplayFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>



            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="row" style="margin: 0px 0px;width: 90%;">
                    <div class="offset-xl-5 offset-lg-5 offset-md-5 offset-sm-2 offset-4">
                        <input id="btnDelete" type="submit" class="btn blue-gradient" name="btnSave" value="Delete" style="border-radius: 15px" />
                    </div>
                </div>
            }
        </div>
    </div>



    <script src="~/Areas/Material_Expenses/js/Add_Material_JS.js"></script>


}

Eskaney/Areas/Housing_Projects/Views/Material/Material_Details.cshtml
@model IEnumerable<Eskaney.Models.Material_Expenses>

@{
    ViewBag.Title = "Material Details";
    Layout = "~/Areas/Housing_Projects/Views/Shared/_Home.cshtml";
}

@section Head{


    <script type="text/javascript">

        $(document).ready(function () {

            $("#Material").addClass("active");

            debugger
            var id = '@TempData["HousingID"]';

            $('#dtBasicExample').DataTable();
            $('.dataTables_length').addClass('bs-select');
        })


        @*function LoadData(id) {

            debugger

            $("#tblMeterial tbody tr").remove();
            $.ajax({
                type: 'Get',
                url: '/Material/getMaterials?id=x'.replace('x', id),
                dataType: 'json',
                success: function (data) {

                    debugger
                    var x = 1;
                    $.each(data, function (i, item) {
                        debugger
                        var MatId = item.id;
                        var txtMatName = item.Material_Name;
                        var txtEnvoiceNum = item.EnvoiceNumber;
                        var txtQuantity = item.Quantity;
                        var txtDate = new Date(parseInt(item.Date.replace("/Date(", "").replace(")/", ""), 0));
                        var txtCoust = item.Coust;
                        var txtNotes = item.Notes;

                        var Day = txtDate.getDate();
                        var Month = txtDate.getMonth() + 1;
                        var Year = txtDate.getFullYear();

                        var rows = "<tr>"
                            + "<td>" + x + "</td>"
                            + "<td>" + txtMatName + "</td>"
                            + "<td>" + txtEnvoiceNum + "</td>"
                            + "<td>" + txtQuantity + "</td>"
                            + "<td>" + Day + "/" + Month + "/" + Year + "</td>"
                            + "<td>" + txtCoust + "</td>"
                            + "<td>" + txtNotes + "</td>"
                            + "<td> <a href='@Url.Action("Edit", "Material", new { id = 1 })' style='color: blue;'> <i class='fas fa-edit'></i>" + 'Edit' + "</a >"
                            + " |   <a href='@Url.Action("Delete", "Material", new { id = 1 })' style='color: red;'> <i class='fas fa-trash'></i>" + 'Delete' + "</a > </td>"
                            + "</tr>";
                        $('#tblMeterial tbody').append(rows);

                        x++;
                    });
                },
                error: function (ex) {
                    var r = jQuery.parseJSON(response.responseText);
                    alert("Message: " + r.Message);
                    alert("StackTrace: " + r.StackTrace);
                    alert("ExceptionType: " + r.ExceptionType);
                }
            });
            return false;
        }*@


    </script>


    <style>
        table.dataTable thead .sorting:after,
        table.dataTable thead .sorting:before,
        table.dataTable thead .sorting_asc:after,
        table.dataTable thead .sorting_asc:before,
        table.dataTable thead .sorting_asc_disabled:after,
        table.dataTable thead .sorting_asc_disabled:before,
        table.dataTable thead .sorting_desc:after,
        table.dataTable thead .sorting_desc:before,
        table.dataTable thead .sorting_desc_disabled:after,
        table.dataTable thead .sorting_desc_disabled:before {
            bottom: .5em;
        }

        tr {
            text-align: center;
        }

        th {
            background-color: #464a5d;
        }
    </style>

}

@section Body{


        @*<h1 class="text-center">Meterial Details</h1>
        <div class="card mb-4">
            <div class="card-header"><h4 style="cursor: default;"><i style="margin-right: 20px;" class="fas fa-hammer mr-4"></i>Meterial Details</h4></div>
            <div class="card-body">
                <div class="table-responsive">
                    <table id="tblMeterial" class="table table-striped table-bordered table-sm" width="100%" cellspacing="0" style="text-align:center;">
                        <thead style="background-color: #a2a0a0;color: white;">
                            <tr>
                                <th></th>
                                <th>Material Name</th>
                                <th>Envoice Number</th>
                                <th>Quantity</th>
                                <th>Date</th>
                                <th>Coust</th>
                                <th>Notes</th>
                                <th></th>
                            </tr>
                        </thead>

                        <tbody>
                        </tbody>

                        <tfoot style="background-color: #a2a0a0;color: white;">
                            <tr>
                                <th></th>
                                <th>Material Name</th>
                                <th>Envoice Number</th>
                                <th>Quantity</th>
                                <th>Date</th>
                                <th>Coust</th>
                                <th>Notes</th>
                                <th></th>
                            </tr>
                        </tfoot>
                    </table>

                </div>
            </div>
        </div>*@








    <h1 class="text-center">Material Details</h1>
        <div class="card mb-4">
            <div class="card-header"><h4 style="cursor: default;"><i style="margin-right: 20px;" class="fas fa-tools mr-4"></i>ManPower Details</h4></div>
            <div class="card-body">
                <div class="table-responsive">
                    <table id="dtBasicExample" class="table table-fixed table-bordered table-sm" cellspacing="0" width="100%" @*id="tblManPower" class="table table-striped table-bordered table-sm" width="100%" cellspacing="0" style="text-align:center;"*@>
                        <thead style="background-color: #a2a0a0;color: white;">
                            <tr>
                                <th class="th-sm" style="width:5px"></th>
                                <th class="th-sm" style="width:60px">Name</th>
                                <th class="th-sm">Material Name</th>
                                <th class="th-sm">Material Source</th>
                                <th class="th-sm" style="width:60px">Quantity</th>
                                <th class="th-sm" style="width:60px">Date</th>
                                <th class="th-sm" style="width:60px">Coust</th>
                                <th class="th-sm">Envoice Number</th>
                                <th class="th-sm">Notes</th>
                                <th class="th-sm"></th>
                            </tr>
                        </thead>

                        <tbody>
                            @{int x = 1;}
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td> @x </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.housing.Project_Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Material_Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Material_Source)
                                    </td>
                                    <td style="width:60px">
                                        @Html.DisplayFor(modelItem => item.Quantity)
                                    </td>
                                    <td style="width:60px">
                                        @Html.DisplayFor(modelItem => item.Date)
                                    </td>
                                    <td style="width:60px">
                                        @Html.DisplayFor(modelItem => item.Coust)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.EnvoiceNumber)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Notes)
                                    </td>
                                    <td>
                                        <a href="@Url.Action("Edit", "Material", new { id = item.ID, @class = item.Housing_ID })" style="color: blue;">
                                            <i class="fas fa-edit"></i>
                                            Edit
                                        </a>
                                        |
                                        <a href="@Url.Action("Delete", "Material", new { id = item.ID })" style="color: red;">
                                            <i class="fas fa-trash"></i>
                                            Delete
                                        </a>

                                    </td>
                                </tr>

                                x++;
                            }

                        </tbody>

                        <tfoot style="background-color: #a2a0a0;color: white;">
                            <tr>
                                <th style="width:5px"></th>
                                <th style="width:60px">Name</th>
                                <th>Material Name</th>
                                <th>Material Source</th>
                                <th style="width:60px">Quantity</th>
                                <th style="width:60px">Date</th>
                                <th style="width:60px">Coust</th>
                                <th>Envoice Number</th>
                                <th>Notes</th>
                                <th></th>
                            </tr>
                        </tfoot>
                    </table>

                </div>
            </div>
        </div>


}