Eskaney/Models/Housing.cs
using Eskaney.CoustomValidation;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Eskaney.Models
{
    //  اسـكـان

    public class Housing
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Required !!")]
        public string Project_Name { get; set; }

        [Required(ErrorMessage = "Required !!")]
        public int Piece_Number { get; set; } // رقم القطعة

        [Required(ErrorMessage = "Required !!")]
        public string Location { get; set; }


        [DataType(DataType.Date)]
        [LisDate] /* ماحطينا الايرور مسج لانو معرفينها داخل الكلاس */
        public DateTime Date { get; set; }

        [Required(ErrorMessage = "Required !!")]
        public int Basin_Number { get; set; }  //  رقم الحوض

        [Required(ErrorMessage = "Required !!")]
        public double Land_Area { get; set; }  // مساحة الارض

        [Required(ErrorMessage = "Required !!")]
        public double Building_Area { get; set; }  // مساحة البناء

        [Required(ErrorMessage = "Required !!")]
        public double Apartments_Total_Area { get; set; } // مساحة الشقق كاملة

        [Required(ErrorMessage = "Required !!")]
        public double Sarvisas_Total_Area { get; set; } // مساحة الخدمات

        [Required(ErrorMessage = "Required !!")]
        public int Number_Of_Floors { get; set; }  // عدد الطوابق

        [Required(ErrorMessage = "Required !!")]
        public int Number_Of_Apartment { get; set; }  // عدد الشقق

        [Required(ErrorMessage = "Required !!")]
        public double Land_Price { get; set; }  // سعر الارض

        [Required(ErrorMessage = "Required !!")]
        public double Land_Registration { get; set; }  // تسجيل الارض

        [Required(ErrorMessage = "Required !!")]
        public double Building_Licence { get; set; } // رخصة البناء

        [Required(ErrorMessage = "Required !!")]
        public double DesignAndEngineering { get; set; } // التصميم والهندسة

        [Required(ErrorMessage = "Required !!")]
        public double Supervision { get; set; } // الاشراف

        public string Logo { get; set; }

        public string Notes { get; set; }



        public List<Apartment> List_Of_Apartments { get; set; }


        public List<ManPowerCoust> List_Of_ManPowerCousts { get; set; }


        public List<Material_Expenses> List_Of_Material_Expenses { get; set; }



        [DisplayName("Country")]
        [ForeignKey("country")]
        public int Country_ID { get; set; }
        public Country country { get; set; }

        [DisplayName("City")]
        [ForeignKey("city")]
        public int City_ID { get; set; }
        public City city { get; set; }

        [DisplayName("Company")]
        [ForeignKey("company")]
        public int Company_ID { get; set; }
        public Company company { get; set; }
    }

    //public class Housing
    //{
    //    public int ID { get; set; }

    //    [Required(ErrorMessage = "Required !!")]
    //    public string Project_Name { get; set; }

    //    [Required(ErrorMessage = "Required !!")]
    //    public int Piece_Number { get; set; } // رقم القطعة

    //    [Required(ErrorMessage = "Required !!")]
    //    public string Location { get; set; }

    //    [Required(ErrorMessage = "Required !!")]
    //    public DateTime Date { get; set; }

    //    [Required(ErrorMessage = "Required !!")]
    //    public int Basin_Number { get; set; } //  رقم الحوض

    //    [Required(ErrorMessage = "Required !!")]
    //    public double Land_Area { get; set; } // مساحة الارض

    //    [Required(ErrorMessage = "Required !!")]
    //    public double Building_Area { get; set; } // مساحة البناء

    //    [Required(ErrorMessage = "Required !!")]
    //    public int Number_Of_Floors { get; set; } // عدد الطوابق

    //    [Required(ErrorMessage = "Required !!")]
    //    public int Number_Of_Apartment { get; set; } // عدد الشقق

    //    [Required(ErrorMessage = "Required !!")]
    //    public double Land_Price { get; set; } // سعر الارض

    //    [Required(ErrorMessage = "Required !!")]
    //    public double Registration_Coast { get; set; } // تكاليف التسجيل والترخيص

    //    public string Notes { get; set; }



    //    public List<Apartment> List_Of_Apartments { get; set; }


    //    public List<Labour_Wages> List_Of_Labour_Wages { get; set; }


    //    public List<Material_Expenses> List_Of_Material_Expenses { get; set; }




    //    [DisplayName("Country")]
    //    [ForeignKey("country")]
    //    public int Country_ID { get; set; }
    //    public Country country { get; set; }

    //    [DisplayName("City")]
    //    [ForeignKey("city")]
    //    public int City_ID { get; set; }
    //    public City city { get; set; }
    //}
}

Eskaney/Areas/Housing_Projects/Controllers/HousingsController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using System.Xml.Schema;
using Eskaney.Models;

namespace Eskaney.Areas.Housing_Projects.Controllers
{
    public class HousingsController : Controller
    {
        private Eskaney_Context db = new Eskaney_Context();

        // GET: Housing/Housings
        [HttpGet]
        public ActionResult Chose_Project(int? id)
        {
            if (Session["Company"] != null)
            {
                var rec = db.Companies.Where(a => a.ID == id).ToList().FirstOrDefault();
                ViewModel vm = new ViewModel();
                TempData["CompanyID"] = rec.ID;
                TempData["CompanyName"] = rec.Name;
                TempData["Logo"] = rec.Logo;
                //vm.List_Of_Housings = new List<Housing>();
                //var housings = db.Housings.Include(h => h.city).Include(h => h.company).Include(h => h.country);
                //return View(housings.ToList());
                //var housing = db.Housings.Where(h => h.ID == id).ToList().FirstOrDefault();
                vm.List_Of_Housings = FillHousings(id);
                return View(vm);
            }
            else
            {
                return RedirectToAction("Login", "Home", new { area = "Home" });
            }
        }

        public List<Housing> FillHousings(int? id)
        {
            List<Housing> housings = db.Housings.Where(a => a.Company_ID == id).Include(h => h.city).Include(h => h.company).Include(h => h.country).ToList();
            return housings;
        }

        public ActionResult Home_Page(int? id)
        {
            if (Session["Company"] != null)
            {
                var rec = db.Housings.Where(a => a.ID == id).ToList().FirstOrDefault();

                TempData["CompanyID"] = rec.Company_ID;

                TempData["HousingID"] = rec.ID;
                ViewBag.ID = rec.ID;

                TempData["ProjectName"] = rec.Project_Name;
                TempData["Logo"] = rec.Logo;

                ViewBag.Logo = rec.Logo;
                var comp = rec.Company_ID;

                var com = db.Companies.Where(a => a.ID == comp).FirstOrDefault();

                TempData["CompanyName"] = com.Name;

                ViewModel VM = new ViewModel();
                
                VM.List_Of_ManPowerCousts = db.ManPowerCousts.Where(q => q.Housing_ID == id).ToList();
                VM.List_Of_Material_Expenses = db.Material_Expenses.Where(a => a.Housing_ID == id).ToList();
               
                return View(VM);
            }
            else
            {
                return RedirectToAction("Login", "Home", new { area = "Home" });
            }
        }

        [HttpGet]
        public JsonResult FillManPowerInfo()
        {
            //var manPowerCousts = db.ManPowerCousts.Select(a => new {

            //    PName = a.Parson_Name,
            //    LName = a.Labour_Name,
            //    Phone = a.Parson_Phone
            //}).ToList();

            //List<ManPowerCoust> manPowerCousts = db.ManPowerCousts.ToList();
            //return Json(manPowerCousts, JsonRequestBehavior.AllowGet);

            var manPowerCousts = db.ManPowerCousts.GroupBy(a => new { a.Parson_Name , a.Labour_Name, a.Parson_Phone}).Select(a=> a.Key).ToList();
            
            return Json(manPowerCousts.ToList(), JsonRequestBehavior.AllowGet);
        }
        


        //List<ManPowerCoust> manPowerCousts = db.ManPowerCousts.Select(x => new {
        //    PName = x.Parson_Name,
        //    LName = x.Labour_Name
        //})
        //            .Distinct();
        // GET: Admin_Page/Admin
        [HttpGet]
        public ActionResult FillHome_Page(int id)
        {
            List<Housing> housings = db.Housings.Where(a => a.ID == id).ToList();

            return Json(housings, JsonRequestBehavior.AllowGet);
        }


        // GET: Housing/Housings/Housing_Info
        [HttpGet]
        public ActionResult Housing_Info(int? id)
        {
            if (Session["Company"] != null)
            {
                var rec = db.Housings.Where(a => a.ID == id).ToList().FirstOrDefault();

                TempData["CompanyID"] = rec.Company_ID;

                TempData["Name"] = rec.Project_Name;
                TempData["HousingID"] = rec.ID;


                

                var com = db.Companies.Where(a => a.ID == rec.Company_ID).FirstOrDefault();
                TempData["CompanyName"] = com.Name;
                ViewBag.Logo = rec.Logo;
                ViewBag.ID = rec.ID;


                return View();
            }
            else
            {
                return RedirectToAction("Login", "Home", new { area = "Home" });
            }
        }

        [HttpGet]
        public ActionResult FillHousing_Info(int id)
        {
            if (Session["Company"] != null)
            {
                List<Housing> housings = db.Housings.Where(a => a.ID == id).ToList();
                return Json(housings, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return RedirectToAction("Login", "Home", new { area = "Home" });
            }
        }


        // GET: Housing/Housings/Housing_Info
        [HttpGet]
        public ActionResult Costs_Info(int? id)
        {
            if (Session["Company"] != null)
            {
                var rec = db.Housings.Where(a => a.ID == id).ToList().FirstOrDefault();

                TempData["CompanyID"] = rec.Company_ID;

                TempData["Name"] = rec.Project_Name;
                TempData["HousingID"] = rec.ID;

                var com = db.Companies.Where(a => a.ID == rec.Company_ID).FirstOrDefault();
                TempData["CompanyName"] = com.Name;
                ViewBag.Logo = rec.Logo;
                ViewBag.ID = rec.ID;



                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                ViewModel VM = new ViewModel();

                // Total Expenses For ManPower  مجموع مصاريف العمال للمشروع    /*  .Sum(a => (double?)a.Coust) ?? 0 بخلي قيمتها 0 في حالة ماكان في داتا */
                double TotalExpensesForManPower = db.ManPowerCousts.Where(a => a.Housing_ID == id).Sum(a => (double?)a.Coust)?? 0;
                ViewBag.TotalExpForManPower = TotalExpensesForManPower;



                // Total Expenses For Material  مجموع مصاريف المواد للمشروع    /*  .Sum(a => (double?)a.Coust) ?? 0 بخلي قيمتها 0 في حالة ماكان في داتا */
                double TotalExpensesForMaterial = db.Material_Expenses.Where(a => a.Housing_ID == id).Sum(a => (double?)a.Coust) ?? 0;
                ViewBag.TotalExpForMaterial = TotalExpensesForMaterial;

                // Total Expenses For the Housing Project  مجموع المصاريف للمشروع
                var TotalExpenses = TotalExpensesForManPower + TotalExpensesForMaterial;
                ViewBag.TotalExpenses = TotalExpenses;




                VM.Housing = db.Housings.Find(id);
                VM.List_Of_ManPowerCousts = db.ManPowerCousts.Where(a => a.Housing_ID == id).ToList();
                VM.List_Of_Material_Expenses = db.Material_Expenses.Where(a => a.Housing_ID == id).ToList();


                if (VM == null)
                {
                    return HttpNotFound();
                }




                return View(VM);

                /************************************************************/

                //var xx = from T in db.ManPowerCousts
                //         where T.Housing_ID == id
                //         orderby T.Parson_Name
                //         group T by T.Parson_Name into g
                //         select new
                //         {
                //             PName = g.Key,
                //             Total = g.Sum(x => x.Coust),

                //         };

                //var CostDet = db.ManPowerCousts.Where(a => a.Housing_ID == id)
                //                          .OrderBy(s => s.Parson_Name)
                //                          .GroupBy(d => d.Parson_Name)
                //                          .Select(ss => new { PName = ss.Key, PCoust = ss.Sum(A => A.Coust) });
                //return View(CostDet.ToList());

                /************************************************************/

            }
            else
            {
                return RedirectToAction("Login", "Home", new { area = "Home" });
            }
        }

        


        [HttpGet]
        public ActionResult SomeSelectedManpowerCosts(int id, string name)
        {
            double powerCousts = db.ManPowerCousts.Where(a => a.Housing_ID == id && a.Parson_Name == name).Sum(a => a.Coust);
            return Json(powerCousts, JsonRequestBehavior.AllowGet);
        }


        // GET: Housing/Housings/Create
        public ActionResult Create(int? id)
        {
            if (Session["Company"] != null)
            {
                ViewModel vm = new ViewModel();
                vm.List_Of_Countries = FillCountries();
                vm.List_Of_Cities = FillCities();
                TempData["CompanyID"] = id;
                return View(vm);
            }
            else
            {
                return RedirectToAction("Login", "Home", new { area = "Home" });
            }
        }

        public List<Country> FillCountries()
        {
            List<Country> countries = db.Countries.ToList();
            return countries;
        }

        public List<City> FillCities()
        {
            List<City> cities = db.Cities.ToList();
            return cities;
        }

        // POST: Housing/Housings/Create

Eskaney/Areas/Housing_Projects/Views/Housings/Chose_Project.cshtml
@*@model IEnumerable<Eskaney.Models.Housing>*@
@model Eskaney.Models.ViewModel

@{
    ViewBag.Title = "Chose Project";
    Layout = "~/Areas/Home/Views/Shared/_Home.cshtml";
}

@section Head{


    <link href="~/Areas/Home/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Areas/Home/fonts/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Areas/Home/fonts/iconic/css/material-design-iconic-font.min.css" rel="stylesheet" />
    <link href="~/Areas/Home/vendor/animate/animate.css" rel="stylesheet" />
    <link href="~/Areas/Home/vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" />
    <link href="~/Areas/Home/vendor/animsition/css/animsition.min.css" rel="stylesheet" />
    <link href="~/Areas/Home/vendor/select2/select2.min.css" rel="stylesheet" />
    <link href="~/Areas/Home/vendor/daterangepicker/daterangepicker.css" rel="stylesheet" />



    <link href="~/Areas/Home/css/util.css" rel="stylesheet" />
    <link href="~/Areas/Home/css/main.css" rel="stylesheet" />
    <!--===============================================================================================-->



    <style>
        @@media (min-width: 768px) {
            .col-md-5 {
                -ms-flex: 0 0 41.666667%;
                flex: 0 0 41.666667%;
                max-width: 37.666667%;
            }
        }

        @@media (min-width: 992px) {

            .col-lg-3 {
                -ms-flex: 0 0 25%;
                flex: 0 0 25%;
                max-width: 24%;
            }
        }

    </style>


    <script type="text/javascript">
        // Stop going back after log off
        //debugger;
        //if (window.history.forward(1) != null)
        //    window.history.forward(1);
        /*******************************/


    </script>


}

@section Body{


    <!-- Full Page Intro -->
    <div class="" style="
        background-image: url('../../../../Image/architecture.jpg');
        background-repeat: no-repeat;
        background-size: cover;
        background-position: center center;">
        <!-- Mask & flexbox options-->
        <div class="mask rgba-gradient align-items-center">

            <div class="container">
                <!--Grid row-->
                <div class="row">
                    <!--Grid column-->
                    <div class="white-text text-center text-md-left mt-xl-8 mb-5 wow fadeInLeft" data-wow-delay="0.3s" style="margin-top: 90px">
                        <!--Grid column-->
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-lg-4 col-md-4 col-sm-5 col-5 offset-lg-1 offset-md-0 offset-2">
                                    <h3 style="width: 150%;padding-top: 30px;">@TempData["CompanyName"] Company</h3>
                                </div>
                                <div class="col-lg-0" style="text-align:center">
                                    @*<h2><img src="@TempData["Logo"]" alt="Alternate Text" width="30" height="50" style=" width: 30%;height: 50%;" /></h2>*@
                                </div>
                                <div class="col-lg-1 col-md-1 offset-md-3" style="text-align:center;margin-top: 30px">
                                    <a href="@Url.Action("Create", "Housings", new { id = TempData["CompanyID"] })" class="btn btn-primary btn-rounded btn-md" title="Click Here To Add New Company">
                                        <i class="fas fa-plus-circle" style="font-size: 170%"></i>
                                        <span style="font-size: large;">New Project</span>
                                    </a>
                                </div>
                            </div>

                           


                        </div>

                        <div class="container">
                            <div class="row">
                                @foreach (var item in Model.List_Of_Housings)
                                {
                                    <div class="card col-lg-3 col-md-5 col-sm-10 col-9 wrap-login100" style="color: black;background-color: #8ec4e8;background-image: linear-gradient(0deg, #140e4ebd 0%, #041f3aad 84%)">
                                        <div class="card-body">
                                            <span class="login100-form-logo">
                                                @*<img src="@Url.Content(item.Logo)" alt="Alternate Text" width="50" height="50" />*@
                                                <img src="~/Image/kindpng_2190861.png" alt="Alternate Text" width="85" height="85" />
                                            </span>
                                            <h5 class="card-title" style="text-align:center;color: white;margin-top: 20px;">@item.Project_Name</h5>
                                            <hr />
                                            <p class="card-text" style="color:white; text-align:center;">Location : @item.Location <br /> Date : @item.Date.Day / @item.Date.Month / @item.Date.Year </p>

                                            <br />


                                            <div class="row">
                                                <small class="text-muted offset-4">
                                                    <a href="@Url.Action("Home_Page", "Housings", new { id = item.ID })" class="btn btn-primary btn-md" style="font: -webkit-small-control;">
                                                        Go
                                                    </a>
                                                </small>
                                            </div>
                                        </div>
                                    </div>

                                }
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </div>

}

Eskaney/Areas/Housing_Projects/Views/Housings/Delete.cshtml
@model Eskaney.Models.Housing

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Home/Views/Shared/_Home.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Housing</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.city.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.city.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.company.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.company.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.country.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.country.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Project_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Project_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Piece_Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Piece_Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Basin_Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Basin_Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Land_Area)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Land_Area)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Building_Area)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Building_Area)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apartments_Total_Area)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apartments_Total_Area)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sarvisas_Total_Area)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sarvisas_Total_Area)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Number_Of_Floors)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number_Of_Floors)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Number_Of_Apartment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number_Of_Apartment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Land_Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Land_Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Land_Registration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Land_Registration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Building_Licence)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Building_Licence)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DesignAndEngineering)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DesignAndEngineering)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Supervision)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Supervision)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Logo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>